<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('ai_generated_questions', function (Blueprint $table) {
            $table->id();
            $table->string('instructor_id')->nullable(); // QU instructor ID
            $table->string('student_id')->nullable(); // QU student ID (if generated by student)
            $table->string('course_no')->nullable(); // Course number from Oracle
            $table->string('course_code')->nullable(); // Course code (e.g., ACCT241)
            $table->integer('questions_count')->default(0); // Number of questions generated
            $table->string('thread_id')->nullable(); // AI thread ID for tracking
            $table->timestamps();
            
            $table->index('instructor_id');
            $table->index('student_id');
            $table->index('course_no');
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ai_generated_questions');
    }
};

