<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AiGeneratedQuestion extends Model
{
    protected $fillable = [
        'instructor_id',
        'student_id',
        'course_no',
        'course_code',
        'questions_count',
        'thread_id',
    ];

    protected $casts = [
        'questions_count' => 'integer',
    ];

    /**
     * Get the user (instructor or student) who generated the questions
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'instructor_id', 'employee_id');
    }

    /**
     * Get the student who generated the questions
     */
    public function student()
    {
        return $this->belongsTo(Student::class, 'student_id', 'student_id');
    }

    /**
     * Record a new AI question generation
     */
    public static function recordGeneration($instructorId, $studentId, $courseNo, $courseCode, $questionsCount, $threadId = null)
    {
        return self::create([
            'instructor_id' => $instructorId,
            'student_id' => $studentId,
            'course_no' => $courseNo,
            'course_code' => $courseCode,
            'questions_count' => $questionsCount,
            'thread_id' => $threadId,
        ]);
    }

    /**
     * Get total questions generated by an instructor
     */
    public static function getTotalByInstructor($instructorId)
    {
        return self::where('instructor_id', $instructorId)->sum('questions_count');
    }

    /**
     * Get total time saved by AI for an instructor (5 minutes per question)
     */
    public static function getTimeSavedByInstructor($instructorId)
    {
        $totalQuestions = self::getTotalByInstructor($instructorId);
        return $totalQuestions * 5; // 5 minutes per question
    }
}

